import React, { useState, useEffect ,useMemo} from "react";
import { useNavigate } from "react-router-dom"; 
import './Header.css';
import { IoSearch } from "react-icons/io5";
import { useTranslation } from 'react-i18next';


 
  function Header() {
    const navigate = useNavigate(); 
    const { t } = useTranslation();

    const [country, setCountry] = useState("");
    const [region, setRegion] = useState("");
    const [category, setCategory] = useState("");
    const [activity, setActivity] = useState("");

    const services = [
      "legume",
      "3G",
      "4G",
      "5G",
      "ADSL",
      "AGRICULTURE",
      "AUTO MOTO",
      "Accessoires",
      "Accompagnateur",
      "Accoudoir central",
      "Acupuncture",
      "Agence",
      "Agent",
      "Agents infectieuses",
      "Agricole",
      "Agroalimentaire",
      "Alarme et traceur GPS",
      "Allergologue",
      "Aluminium",
      "Ampoules LED",
      "Aménagement",
      "Anatomo-cytopathologiste",
      "Anesthésiste-réanimateur",
      "Animateurs",
      "Antivol",
      "Apprentissage automatique",
      "Architecte",
      "Architecte de l'intérieur",
      "Arduino",
      "Argent",
      "Article Bébé et Maman",
      "Artisan bijoutier",
      "Artisanat",
      "Aspirateur",
      "Assurances",
      "Athlétisme",
      "Attelage",
      "Auxiliaire de vie",
      "Avocat",
      "Aérobic",
      "BATIMENT",
      "Baby Sitter",
      "Bannière Publicitaire",
      "Barres de toit",
      "Base de données et gestion des données",
      "Baseball",
      "Basket-ball",
      "Batteries de cuisine",
      "Batteur",
      "Big Data et analyse de données",
      "Bijouterie",
      "Billard",
      "Biologie de la reproduction",
      "Biologiste générale",
      "Biologiste médicale",
      "Blender",
      "Blockchain et cryptomonnaies",
      "Boucherie",
      "Boulangerie",
      "Boutique divers",
      "Bowling",
      "Boxe",
      "Boîtes de conservation",
      "Bricoleur",
      "Bâche de protection",
      "C++",
      "CMS",
      "CSS",
      "Cafetière",
      "Caméra 360°",
      "Caméra de bord",
      "Carraffe",
      "Cave à vin",
      "Centre commerciaux",
      "Centre d'handicapés",
      "Chaise",
      "Charcuterie",
      "Chargeur allume-cigare USB",
      "Chaudière",
      "Chauffage",
      "Chauffe Bain",
      "Chaussures",
      "Chirurgien maxillo facial stomatologue",
      "Chirurgien orale",
      "Chirurgien orthopédiste traumatologue",
      "Chirurgien pediatrique",
      "Chirurgien thoracique et cardiovasculaire",
      "Chirurgien vasculaire",
      "Chirurgien viscérale et digestive",
      "Cinéma",
      "Circoncision",
      "Clignotants dynamiques",
      "Climatiseur",
      "Climeur",
      "Cloud computing (Informatique en nuage)",
      "Club Robotique",
      "Club vélo",
      "Clés à La Minute",
      "Conception",
      "Congélateur",
      "Construction",
      "Costume Enfant",
      "Costumes",
      "Courtier",
      "Couteau Électrique",
      "Couvre-volant anti-dérapant",
      "Coworking space",
      "Cric et clé démonte-roue",
      "Crémerie",
      "Crêpière",
      "Cuisinière",
      "Cyclisme",
      "Câbles de démarrage",
      "DJ",
      "DROIT",
      "DVR",
      "Dames",
      "Danse",
      "Davin",
      "Dayton",
      "Dermatologue",
      "Diffuseur",
      "Diffuseur d'arôme",
      "Doussard",
      "Décoration",
      "Décoration de fête",
      "Déflecteurs de vent",
      "Défroisser Vertical",
      "Déménagement",
      "Désinsectiseur",
      "Désodorisant voiture",
      "ECMO",
      "EDUCATION",
      "ESTHETIQUE",
      "EVENEMENTIEL",
      "Eaux minérales et boissons gazeuses",
      "Educateur",
      "Electricien",
      "Endocrinologue-diabétologue-nutritionniste",
      "Enfant",
      "Enseignant",
      "Entraîneur",
      "Entreprise de désinfection",
      "Equipe",
      "Escrime",
      "Etablissement prive",
      "Extincteur de voiture",
      "Faux plafond",
      "Femme",
      "Femme de ménage",
      "Fer a repasser",
      "Ferrailleurs",
      "Feux de jour et antibrouillards",
      "Fibre optique",
      "Film teinté pour vitres",
      "Fleuriste",
      "Foire",
      "Football",
      "Four",
      "Fournisseur médical",
      "Fourniture scolaire",
      "Fournitures broderie",
      "Français",
      "GASTRONOMIE",
      "GROSSISTE - DEPOT",
      "GSM",
      "Generaliste",
      "Gilet de sécurité",
      "Golf",
      "Grattoir à glace",
      "Gymnastique",
      "Gynécologue",
      "Gynécologue obstrétricien",
      "Génie civil",
      "Généticien",
      "HTML",
      "Hachoir",
      "Handball",
      "Handmade",
      "Homme",
      "Hotte",
      "Housses de rétroviseurs",
      "Huissiers",
      "Humidificateur et Purificateur d'air",
      "Hématologue",
      "Hématologue et immunologiste",
      "Hépato-gastro-entérologue",
      "INFORMATIQUE",
      "Importer",
      "Informatique embarquée",
      "Informatique quantique",
      "Ingénierie logicielle",
      "Ingénieur de béton",
      "Inscription Scolaire",
      "Installation",
      "Intelligence artificielle (IA)",
      "Internet des objets (IoT)",
      "Jardinier",
      "Jet ski",
      "Jiu-jitsu",
      "Jouets",
      "Joueur",
      "Judo",
      "Karaté",
      "Karting",
      "Kayak",
      "Kick-boxing",
      "Kit anti-crevaison",
      "Kung fu",
      "LOISIR",
      "Lancer de disque",
      "Lancer de javelot",
      "Lancer de marteau",
      "Lancer de poids",
      "Lave Vaisselle",
      "Librairie",
      "Location de costumes et des robe de fête",
      "Location de matériel de construction",
      "Location de matériel de fête",
      "Lumière et câble",
      "L’entretien en mécanique navale",
      "MARCHÉ",
      "MDF",
      "METIERS",
      "Machine Learning",
      "Machine à Coudre",
      "Machine à Glace & Sorbetières",
      "Machine à Laver",
      "Machine à pain",
      "Maison",
      "Maladies infectieuses et tropicales",
      "Maquillage",
      "Marathon",
      "Marche",
      "Marchepieds",
      "Maçon",
      "Menuisier",
      "Meuble",
      "Micro Onde",
      "Mini Réfrigérateur",
      "Mixeur",
      "Moto (cross)",
      "Moulin à Epices",
      "Musculation",
      "Musk",
      "Mécanique navale",
      "Médecine cardiovasculaire",
      "Médecine du sport",
      "Médecine du travail",
      "Médecine généraliste",
      "Médecine intensive-réanimation",
      "Médecine interne",
      "Médecine moléculaire, génétique et pharmacologie",
      "Médecine nucléaire",
      "Médecine physique réadaptateur",
      "Médecine vasculaire",
      "Natation",
      "Nettoyeur à Vapeur",
      "Nettoyeur à haute pression",
      "Neurochirurgien",
      "Neurologue",
      "Nintendo",
      "Notaire",
      "Néphrologue",
      "Oncologue",
      "Ophtalmologiste",
      "Organisateur de siège",
      "Oto-Rhino-Laryngologiste",
      "Outeya",
      "PDG",
      "PHP",
      "Padel",
      "Paintball",
      "Parabole",
      "Parachutisme",
      "Pare-brise chauffant",
      "Pare-soleil",
      "Parfumerie",
      "Parie / beat",
      "Parkour",
      "Paysagistes",
      "Peintre",
      "Pilotage",
      "Ping-Pong",
      "Placo",
      "Plastique",
      "PlayStation",
      "Plombier",
      "Plongeur",
      "Pneumologue",
      "Polo",
      "Pommeau de levier de vitesse personnalisé",
      "Porte-vélos",
      "Pressing",
      "Produits cosmétiques",
      "Professeurs",
      "Promotion immobilière",
      "Préparateurs physique",
      "Préparateurs radio et télévision",
      "Prêt à porter",
      "Ps",
      "Psychiatre",
      "Purificateur d’air",
      "Pâtissier",
      "Pédiatrie",
      "Pétanque",
      "Radar de recul",
      "Radiologue et imagerie médicale",
      "Rallye automobile",
      "Raspberry PI",
      "Reamenagement",
      "Recherche",
      "Restaurant à la carte",
      "Rhumatologue",
      "Robe Fille",
      "Robe Soiree",
      "Robe de mariage",
      "Robot Multifonction",
      "Robot Pétrin",
      "Robotique et automatisation",
      "Route de Secours",
      "Rugby",
      "Réfrigérateur",
      "Réparation",
      "Réseaux informatiques",
      "Rétroviseur avec écran intégré",
      "SANTE",
      "SCANNERS",
      "SECURITE",
      "SERVICES",
      "SHOPPING",
      "SPORT",
      "SQL",
      "Salle",
      "Santé publique",
      "Saut en hauteur",
      "Saut en longueur",
      "Saut à la perche",
      "Serveurs",
      "Skateboard",
      "Société évènementielle",
      "Soudeur",
      "Souffleur d'air pour nettoyage",
      "Sourd et muet",
      "Spoiler et aileron",
      "Spéléologie",
      "Stérilisateur",
      "Super fripe",
      "Supports pour téléphone et GPS",
      "Surf",
      "Systèmes d'exploitation",
      "Sèche Linge",
      "Sécurité informatique et cybersécurité",
      "Sécurité logiciel",
      "TEP",
      "TOURISME",
      "TRANSPORT",
      "Table de Cuisson",
      "Tapissiers",
      "Tennis",
      "Tir à l'arc",
      "Topographe",
      "Traducteur",
      "Traitement du langage naturel (NLP)",
      "Triangle de signalisation",
      "Trousse de premiers secours",
      "USINE",
      "UX/UI",
      "Urbaniste",
      "Urologue",
      "VDSL",
      "Vendeur d’articles de sport",
      "Vente de matériel de construction",
      "Vente tenus de travail",
      "Ventilateurs",
      "Voile",
      "Volant sport ou gainé",
      "Volley-ball",
      "Vélocross",
      "Vêtement Th'our",
      "Vêtements",
      "Water-polo",
      "Wordpress",
      "Xénon",
      "Yoga",
      "Zumba",
      "abat jour",
      "acajou",
      "accessoires",
      "accueil",
      "achat de terrain",
      "acide hyaluronique",
      "acier inoxydable",
      "acteur",
      "activité",
      "actrice",
      "adaptable",
      "adaptés",
      "administration",
      "affaire",
      "agence de sécurité",
      "agent",
      "agneau",
      "agroalimentaire",
      "ail",
      "air fraiche",
      "alarmes",
      "alimentations generales",
      "alliages d'aluminium de fonderie",
      "alliages d'aluminium pour corroyage",
      "allô taxi",
      "amande",
      "ambres",
      "amethyste",
      "amortisseur",
      "aménagement d'intérieur",
      "analyse du marche",
      "anglais",
      "animation",
      "animation anniversaire",
      "animation des fête",
      "animation enfant",
      "animation scène",
      "animations",
      "anneaux",
      "antenne",
      "anti cerne",
      "anti feu",
      "anti humide",
      "anti-javel",
      "anticerne",
      "antique",
      "antiquités",
      "appareil a dialyse",
      "appareils a rayons x",
      "appareils chirurgicaux lasik",
      "applications",
      "applications mobile",
      "arabe",
      "arbuste",
      "architecture",
      "argent",
      "armoire",
      "article d'anniversaire",
      "article en Crystal",
      "article en bois",
      "articles de plage",
      "artiste",
      "assiette",
      "assurance",
      "autiste",
      "autocad",
      "bac",
      "bague",
      "bagues",
      "baguette",
      "band",
      "band musical",
      "barrette mémoire",
      "batterie",
      "baume a lèvre",
      "baume a lèvres",
      "beton",
      "beurre",
      "bibliothèque",
      "bicyclette",
      "bijoux",
      "bineuse",
      "biscuit",
      "blender",
      "bloc d'alimentation",
      "bloc- notes",
      "blocs",
      "blouson",
      "blé",
      "bois",
      "boiseries",
      "boissons gazeuses",
      "boite",
      "boite archives",
      "boite vitesse",
      "boitier",
      "bols",
      "bonbon",
      "bonbon d’enfants",
      "bonnet",
      "bons",
      "bootstrap",
      "boucher",
      "bouchons",
      "boucle",
      "boucle d'oreille",
      "bougies led",
      "bouquet fleur décoratif",
      "boutons",
      "bracelet",
      "bracelets",
      "brik",
      "brique",
      "briques",
      "brise",
      "broche",
      "brochette",
      "bronze",
      "brownies",
      "burger",
      "business",
      "bœuf",
      "cabinet de douche",
      "cacahuète",
      "cafard",
      "café",
      "cahier",
      "cake",
      "calamar",
      "camera",
      "camion",
      "canape",
      "cane",
      "capsule",
      "capteur pression de carburant",
      "carafe",
      "carotte",
      "carrelage",
      "carte graphique",
      "carte mère",
      "carte mémoire",
      "carton",
      "casquette",
      "casting",
      "chahia",
      "chaines",
      "chaise",
      "chambre",
      "chanteur",
      "chantier",
      "chapati",
      "chargeur",
      "charms",
      "charpentier métallique",
      "chaussure",
      "chaussures",
      "chaussures de sécurité",
      "chawarma",
      "chef",
      "chef de chaine",
      "chemin",
      "chemise",
      "chicha",
      "chichkhane",
      "chien",
      "chimie",
      "chirurgie de l'obésité",
      "chirurgie de la silhouette",
      "chirurgie de visage",
      "chirurgie esthétique",
      "chirurgie mammaire",
      "choc",
      "choc électrique",
      "chocolat",
      "ciments",
      "citerne",
      "citronnade",
      "classeur",
      "clavier",
      "client",
      "clé USB",
      "clés",
      "cnam",
      "cocktail de vitamine",
      "code IPTV",
      "coffret",
      "coiffeur femme",
      "coiffeur homme",
      "collaboration",
      "collier",
      "coloration",
      "coloration sourcils",
      "commerce",
      "commis",
      "compteur",
      "confection",
      "conférence",
      "conseil",
      "conservations",
      "console",
      "construction",
      "construction fenêtres",
      "constructions",
      "contrat d'achat",
      "contrat de location",
      "contrat de mariage",
      "contrat de vente",
      "contrôle d'accès",
      "conventionne",
      "corail",
      "coraille",
      "cordon",
      "cordon bleu",
      "correction",
      "costume",
      "couette",
      "coupe",
      "couple moteur",
      "couscous",
      "cout d'éclat de la peaux",
      "couture",
      "crayon a lèvres",
      "crayon a sourcils",
      "crayon pour les yeux",
      "crayons",
      "crepe sale",
      "crevette",
      "cristeaux swarovski",
      "crochet",
      "croissant",
      "crème hydratant",
      "crème hydratante",
      "création",
      "crêpe sale",
      "crêpe sucrée",
      "cuir",
      "cuisine",
      "cuisine interne",
      "cuisine sur mesure",
      "cuivre",
      "culbuteurs",
      "cultivateur",
      "cumin",
      "cumin beurre",
      "curcuma",
      "curoir d’alternateur",
      "cuvette de toilettes",
      "cycles",
      "câble",
      "câble HDMI",
      "câble électrique",
      "céramique",
      "céréale",
      "céréales",
      "cérémonie",
      "côtelette",
      "dance",
      "dancers",
      "dart",
      "dashcam",
      "dentisterie esthétique",
      "design",
      "designer",
      "dessert",
      "devOps",
      "diamant",
      "directeur",
      "direction",
      "divorce",
      "django",
      "docteur",
      "document",
      "domiciliation",
      "dommage au location",
      "drap",
      "dreamcatcher",
      "droit",
      "droit de la famille",
      "droit du travail",
      "déco",
      "décor",
      "décor anniversaire",
      "décor fête spécial",
      "décor salle",
      "décor tasdira arrousa",
      "décor thour",
      "décoration",
      "défendent",
      "démaquillant",
      "démarreur",
      "déplacement",
      "désinfection",
      "désinfection des surfaces",
      "détient le monopole",
      "développeur",
      "développeur logiciels",
      "développeur mobile",
      "développeur web",
      "développeurs",
      "eaux minérales",
      "ecaille de tortue",
      "eclairage",
      "electricite generale",
      "electrique",
      "emballage",
      "emballage de sardine",
      "emballage thon",
      "emboîtage",
      "embrayage",
      "emeraude",
      "enfant",
      "ensileuse",
      "entretien",
      "entrée",
      "enveloppes et pochettes",
      "equipe",
      "escalope",
      "espace",
      "essieux",
      "expert juridique",
      "exécutions",
      "eyeliner",
      "faculté",
      "fard a joues",
      "fard a joues(blush)",
      "fard a paupière",
      "fard a paupières",
      "faïence",
      "femme",
      "fenêtres",
      "fer",
      "fermoirs",
      "fiançailles",
      "figma",
      "film",
      "fils",
      "firebase",
      "flash disk",
      "fleur (mariage , fête )",
      "flutter",
      "foie",
      "foie de poulet",
      "fond de teint",
      "fondant",
      "forfait",
      "formation",
      "forme",
      "foulards",
      "fourrage",
      "frais poulet",
      "freinage",
      "freins",
      "fricasse",
      "frigo",
      "fripe",
      "fromage",
      "fromage râpe",
      "fruits",
      "fête",
      "fête privée",
      "gaming",
      "garde",
      "gel",
      "gel nettoyant",
      "gigabyte",
      "gilet",
      "gilet royale",
      "gingembre",
      "givrer",
      "gloss",
      "gommage",
      "gouttières",
      "graines",
      "greffe de cheveux fue",
      "grive",
      "gros électroménager",
      "gruyère",
      "gâteau",
      "gâteaux",
      "génie civil",
      "géolocalisations",
      "gérer les appels téléphoniques",
      "gérer les problème de voiture",
      "habillage",
      "handicape",
      "harissa",
      "harkous",
      "healthy",
      "henna",
      "hergma",
      "highlighter",
      "hlelem",
      "homme",
      "hosting",
      "huile",
      "huiles essentiel",
      "hygiène",
      "hébergement",
      "illustrator",
      "images",
      "immeubles",
      "imperméable",
      "imprimante",
      "in design",
      "info",
      "installation de chauffage",
      "installation parabole",
      "installation sanitaire",
      "installation électrique",
      "interface",
      "interieur",
      "intermédiaire",
      "internet",
      "jambon",
      "jardinage",
      "java",
      "javaScript",
      "jeans",
      "jeux",
      "jeux de cartes",
      "jeux et jouets",
      "joint de cache",
      "jouets",
      "jouets éducatifs",
      "jus",
      "justice",
      "kafteji",
      "kaki",
      "kamouneya",
      "karwia",
      "kempo",
      "khôl",
      "kit de distribution",
      "la production de vapeur",
      "la production d’eau douce",
      "lait",
      "laiton",
      "lampe",
      "langouste",
      "lasagne",
      "laser",
      "lasers médicaux",
      "laurier",
      "lavage a sec",
      "lavage de voiture",
      "lavage de voiture et vidange",
      "lban",
      "le détachage des sols et mur",
      "leasing",
      "lecture",
      "les assiettes",
      "les bagues",
      "les bains",
      "les boissons",
      "les bougies",
      "les ceintures",
      "les chapeaux",
      "les chargeur",
      "les conserve",
      "les disque dur et SSD",
      "les fruits secs",
      "les injecteurs",
      "les issues des eaux",
      "les jus frais",
      "les ordinateurs portable",
      "les pates",
      "les robes",
      "libanais",
      "ligneur(eye liner)",
      "livre",
      "localisation",
      "location",
      "location de espace",
      "logiciel",
      "logo",
      "loisirs",
      "lotions",
      "loup",
      "lumière",
      "lunette masque",
      "lustres",
      "machine a bêcher",
      "machine agricole",
      "machine auxiliaires",
      "madfouna",
      "maison d’abeilles",
      "makloub",
      "malade",
      "manette",
      "mannequin",
      "manteaux",
      "maquillage",
      "margoum",
      "mariage",
      "maroquinerie",
      "marqueurs",
      "mascara",
      "matelas",
      "materiel",
      "math",
      "matériel d'usine",
      "mazraa",
      "menu de jours",
      "merguez",
      "metiers du batiment",
      "meuble",
      "meuble chaussures",
      "meuble tv",
      "meubles",
      "microblading",
      "micronnedling",
      "mini gâteaux",
      "mise en place",
      "mlewi",
      "mloukeya",
      "mongodb",
      "montre",
      "moquette",
      "motoculture",
      "moules",
      "moulin a huile",
      "mousse aux chocolat",
      "moustique",
      "movie",
      "mozzarella",
      "multi brise",
      "mur",
      "music",
      "mySQL",
      "mécanique automobile",
      "méche",
      "médecin de la famille",
      "médecin généraliste",
      "nakcha",
      "nature",
      "nest.js",
      "nettoyage",
      "nettoyage de peaux",
      "nettoyage de peaux a la vapeur",
      "nettoyage en profondeur de peau",
      "neuf",
      "next.js",
      "node.js",
      "noisette",
      "nourriture",
      "nuitée",
      "nwasser",
      "occasion",
      "odoo",
      "office complexes",
      "officier ministériel",
      "oignon",
      "olive",
      "onglerie",
      "opale",
      "or",
      "ordinateur de bureau",
      "ordinateur portable",
      "ordinateurs",
      "organisaient",
      "organisation",
      "organza",
      "os",
      "ous de lit",
      "ouvrier",
      "oxygénation de la peau",
      "pain",
      "pain au chocolat",
      "pain aux chocolat",
      "pain complet",
      "palette",
      "pantalon",
      "pantalons",
      "papeterie",
      "papier bulle",
      "papier paient",
      "par heure",
      "parfum",
      "parquets",
      "passoire",
      "pc",
      "pdg",
      "peinture",
      "peluches",
      "perle",
      "perles",
      "perles a enfiler",
      "perles de culture",
      "perles de verre",
      "perles en ceramique",
      "perles en plastique",
      "permanence",
      "persil",
      "petit déjeuner",
      "petit pain",
      "petites maçonneries",
      "photo gravée",
      "photocopie",
      "photos",
      "photoshop",
      "physique",
      "piercing",
      "piercing nez",
      "piercing oreille",
      "piercing sourcil",
      "pierres artificielles",
      "pierres naturelles",
      "piments",
      "pinceau",
      "pinces a bijoux",
      "pistache",
      "pistons",
      "pizza",
      "pièce de rechange",
      "plan",
      "plantations",
      "plante artificielle",
      "plantes",
      "plantes artificielle",
      "plantes décor",
      "plants",
      "plastique",
      "plateau",
      "platine",
      "plats",
      "plomberie",
      "plongée  sous-marine",
      "poisson",
      "poivre",
      "pollen",
      "pompe de gavage",
      "pompes a perfusion",
      "pop corn",
      "port manteau",
      "portable",
      "porte - blocs",
      "porte clés",
      "portefeuilles",
      "portes",
      "portes clés",
      "poterie",
      "poulet frais",
      "poulet mechwi",
      "poumon d'acier",
      "poupées",
      "poussette",
      "presse",
      "production électricité",
      "produit cosmétique",
      "produit d'étanchéité",
      "produit de soin",
      "produit décoratif",
      "produits cosmétique",
      "produits de lego",
      "programme",
      "projecteur",
      "promenade",
      "promo",
      "propolis",
      "propulsion des navires",
      "prospection",
      "protection",
      "prépa",
      "puce",
      "pulls",
      "puzzles",
      "python",
      "pâtes",
      "pâtisserie",
      "pépinière des plantes",
      "pêcheur",
      "quartz",
      "racines",
      "radia facial",
      "radio",
      "raib",
      "rames papier",
      "randonne",
      "randonnée",
      "rangement",
      "react",
      "react native",
      "rechta",
      "registres",
      "regroupement céréales",
      "regroupement laitière",
      "remorque",
      "renovation",
      "reparation",
      "reservation",
      "resine epoxy",
      "restaurant",
      "robe soirée",
      "robotique",
      "roquefort",
      "roues",
      "rouge a lèvre",
      "rouge a lèvres",
      "rouleau",
      "rubanerie",
      "rubans",
      "rubis",
      "récepteur",
      "réception",
      "régulateur de ralenti",
      "réparation imprimante",
      "réseau",
      "réseau informatique",
      "réservation",
      "réservations",
      "réunion",
      "sable",
      "sac",
      "sac a dos",
      "sac a main",
      "sac et landau",
      "salade",
      "salami",
      "salle de fête",
      "salon",
      "sandwich",
      "saphir",
      "sardines",
      "satin",
      "saumon",
      "scanner",
      "schéma",
      "scène",
      "seau",
      "semoules",
      "serveurs",
      "service",
      "service d'hygiène",
      "service prestige",
      "service stations",
      "shopping malles",
      "sicilien",
      "sieste",
      "site web",
      "siège auto",
      "sièges",
      "sman",
      "smart",
      "smart phone",
      "soirée",
      "sol",
      "sommeil",
      "sonorisation",
      "souder a l'arc",
      "souder fer",
      "sourcils",
      "souris",
      "sous souris",
      "sous vêtements",
      "soutien scolaire",
      "soutient scolaire",
      "spirale",
      "spot lumière",
      "spray",
      "spray fixateur",
      "spécialité locale",
      "steak",
      "stockage",
      "styliste modéliste",
      "stylo",
      "stylo électrique",
      "succession",
      "suite",
      "suivi",
      "superviseur",
      "supervision",
      "support moteur",
      "sur mesure",
      "sur-mesure",
      "surfa Caire",
      "suspension",
      "système de lubrification",
      "systèmes HVAC",
      "sécurité",
      "séparation",
      "tabac",
      "tabel",
      "table",
      "table décoration",
      "tableau",
      "tablettes",
      "tablier",
      "tabouret",
      "tacos",
      "taille crayons",
      "tailwind",
      "tajine",
      "tapie et rideaux",
      "tapis",
      "tapis cuisine",
      "tarifs hebdomadaire",
      "tarifs mensuel",
      "tasdira",
      "tasses",
      "tatouage",
      "tatouage sourcil",
      "teinture",
      "tenue apiculteur",
      "terrassements",
      "textile",
      "thon",
      "thé",
      "ticket de recharge",
      "tickets",
      "tirage",
      "tiramisu",
      "tissu",
      "tissu anti tache",
      "tissus",
      "titane",
      "tomate",
      "tomate concentre",
      "tomodensitomètres",
      "top modèle",
      "tourisme",
      "tracteur",
      "traduire en plusieurs langue",
      "traduire les contrat",
      "traduire les diplôme",
      "traitement de visage",
      "traites les bouton d'acné",
      "traites les imperfection",
      "transport",
      "travaux",
      "tricot",
      "tricycles",
      "turquoise",
      "tv smart",
      "téléconseillers",
      "téléphonie",
      "télésurveillance",
      "téléviseur",
      "télévision",
      "ultra-sons IRM",
      "uniforme",
      "usine",
      "utilise",
      "vaisselle",
      "vedette",
      "vente",
      "vente de fer",
      "vente matériel agriculture",
      "ventilateur médical",
      "vernis",
      "vernis a ongles",
      "vernis permanent",
      "vernis à angle",
      "verre",
      "verres",
      "veste",
      "viande",
      "viennoiserie",
      "vieux",
      "vins",
      "visual basic",
      "vitrine",
      "voiture",
      "vol",
      "volant",
      "voyage",
      "vêtement",
      "vêtement Traditionnel (jeba , koftan)",
      "vêtements",
      "web designer",
      "yaourt",
      "zinguerie",
      "Échecs",
      "Éclairage intérieur LED",
      "Édam",
      "Électroménager",
      "Épicerie",
      "Équitation",
      "Étanchéité",
      "écharpes",
      "éclat de peaux",
      "éclat de teint",
      "écran",
      "éducation",
      "électricien d'équipement industriel",
      "électricien du tertiaire",
      "électricité",
      "électroménager",
      "électroménagers",
      "électronique",
      "élevage",
      "élimination des bouton noir et des rougeur",
      "élimine les boutons noir",
      "épanché",
      "épices",
      "épilation",
      "épilation corps complet",
      "épilation laser",
      "épilation laser définitive",
      "épinards",
      "équipement de diagnostic",
      "équipement médical de laboratoire",
      "équipement thérapeutique",
      "équipement vital",
      "équipement électrique",
      "étagère",
      "étancheur",
      "étanchéité a l'eau",
      "étiquette de langue",
      "éveil et toilette",
      "œuf"
  ]
   
    const countries = ["Tunisie", "Algérie", "Maroc", "Libye", "Egypte"];
    const  regions_tunisie = [
      "Ariana",
      "Beja",
      "Ben Arous",
      "Bizerte",
      "Gabès",
      "Gafsa",
      "Jendouba",
      "Kairouan",
      "Kasserine",
      "Kébili",
      "Kef",
      "Mahdia",
      "Manouba",
      "Medenine",
      "Monastir",
      "Nabeul",
      "Sfax",
      "Sidi Bouzid",
      "Siliana",
      "Sousse",
      "Tataouine",
      "Tozeur",
      "Tunis",
      "Zaghouan"
  ]
  
    const categories = [
  "Clinique",
  "SOS Infirmerie",
  "Pharmacie",
  "Ambulance",
  "Centre médicale",
  "Kiné",
  "Infermier",
  "Nutritionniste",
  "Opticien",
  "Laboratoire",
  "Auxiliére de vie",
  "Paramédicale",
  "Vétérinaire",
  "Technicien de matériel",
  "Notaire",
  "Huissiers",
  "Traducteur",
  "Experts",
  "Conseiller juridique d'entreprise",
  "Architecte",
  "Ingénieur de béton",
  "Architecte de l'intérieur",
  "Génie civil",
  "Promotion immobilière",
  "Entrepreneur",
  "Cuisine sur mesure",
  "Urbaniste",
  "Paysagistes",
  "Topographe",
  "Location de matériel de construction",
  "Vente de matériel de construction",
 "Maçon",
 "Électricien",
 "Plombier",
 "Menuisier",
 "Étanchéité",
 "Aluminium",
 "Forgeron",
 "Chaud Froid",
 "Réparation électroménager",
 "Artisan bijoutier",
 "Jardinier",
 "Pâtissier",
 "Femme de ménage",
 "Baby sitter",
 "Courtier",
 "Faux plafond",
"Placo",
"Parabole",
"Soudeur",
"Vitrerie",
"Tapissiers",
"Préparateurs radio et télévision",
"Charpentier métallique",
"Plongeur",
"Pêcheur",
"Fleuriste",  
  "Centre commerciaux",
  "Bijouterie",
  "Super fripe",
  "Boutique divers",
  "Produits cosmétiques",
  "Parfumerie",
  "Artisanat",
  "Handmade",
  "Importer",
  "Cinéma",
  "Café",
  "Salon de thé",
  "Parc de loisirs",
  "Espace familiale",
  "Théâtre",
  "Festival",
  "Disco",
  "Cirque",
  "Rando et camping",
  "Agroalimentaire",
  "Construction",
  "Vêtements",
  "Accessoires",
  "Décoration",
  "Lumière et câble",
  "Maquillage",
  "Fournisseur médical",
  "Électroménager",
  "Article Bébé et Maman",
  "Plastique",
  "Jouets",
  "Informatique",
  "Agriculture",
  "Meuble",
  "Fourniture scolaire",
  "Eaux et boissons gazeuses",
  "Boulangerie",
  "Boucherie",
  "Charcuterie",
  "Crémerie",
  "Épicerie",
  "Poissonnerie",
  "Vendeur fruits et légumes",
  "Poulailler",
  "Magasin",
  "Drug store",
  "Vente du miel",
  "Supermarché",

  
  "Établissement privé",
  "Accompagnateur",
  "Enseignant",
  "Professeurs",
  "Centre de formation",
  "Club Robotique",
  "Coworking space",
  "Centre d'handicapés",
  "Coiffure",
  "Centre de remise en forme",
  "Estheticienne",
  "Epilation",
  "Centre d'esthétique",
  "Onglerie",
  "Chirurgie esthétique",
  "Piercing",
  "Tatouage",
  "Lazer",
  "Microneedling",
  "Salle des fêtes",
  "Location de costumes et des robes de fête",
  "Location de matériel de fête",
  "Serveurs",
  "Animateurs",
  "Foire",
  "Décoration des fêtes",
  "Société événementielle",
  "Taxi",
  "Location de voitures",
  "Grand Taxis",
  "Taxi moto",
  "Louage",
  "Transport Maritime",
  "Vente et installation des caméras et alarmes",
  "Agence de sécurité",
  "Location de matériel",
  "Athlétisme",
  "Aérobic",
  "Baseball",
  "Basket-ball",
  "Billard",
  "Bowling",
  "Boxe",
  "Cyclisme",
  "Club vélo",
  "Danse",
  "Dames",
  "Échecs",
  "Équitation",
  "Escrime",
  "Football",
  "Golf",
  "Gymnastique",
  "Handball",
  "Judo",
  "Jiu-jitsu",
  "Jet ski",
  "Karaté",
  "Kempo",
  "Karting",
  "Kayak",
  "Kick-boxing",
  "Kung fu",
  "Lancer de disque",
  "Lancer de javelot",
  "Lancer de marteau",
  "Lancer de poids",
  "Marche",
  "Moto Cross",
  "Musculation",
  "Marathon",
  "Natation",
  "Paintball",
  "Parkour",
  "Pétanque",
  "Ping-Pong",
  "Polo",
  "Rallye automobile",
  "Rugby",
  "Saut à la perche",
  "Saut en hauteur",
  "Saut en longueur",
  "Skateboard",
  "Spéléologie",
  "Surf",
  "Tennis",
  "Tir à l'arc",
  "Vélocross",
  "Voile",
  "Volley-ball",
  "Water-polo",
  "Yoga",
  "Zumba",
  "Equipe",
  "Joueur",
  "Agent",
  "Salle",
  "Préparateurs physique",
  "Educateur",
  "Entraîneur",
  "Vendeur d'articles de sport",
  "Parie bet",

  
  "Vente de matériel informatique",
  "Développeur",
  "Réparation portable",
  "Maintenance informatique",
  "Boite de développement",
  "Data analyste",
  "Montage vidéo",
  "Designer",
  "Cybersécurité",
  "Infographiste",
  "Centre d'appel",
  "Freelance",
  "Publinet",
  "Imprimerie",
  "Hôtel de charme",
  "Hôtel de ville",
  "Hôtel",
  "Agence de voyage",
  "Maisons d'hôtes",
  "Base nautique",
  "Acteur",
  "Actrice",
  "Chanteurs",
  "Artiste de ville",
  "Portraitrice",
  "Écrivain",
  "Poète",
  "Musicien",
  "Musée",
  "Galerie",
  "Vente instrument de musique",
  "Agricole",
  "Sondage",
  "Moulin des épices",
  "Location matériel agricole",
  "Regroupement laitière",
  "Regroupements céréales",
  "Vente matériel agriculture",
  "Pépinières des plantes",
  "Moulin à huile",
  "Vente matériel électronique",
  "Matériel parabolique",
  "Enseigne Lumineuse",
  "Matériels électroménager",
  "Lustres",
  "Quincaillerie",
  "Banque",
  "Comptable",
  "Financier",
  "Leasing",
  "Recouvrement",
  "Ste des cartes magnétiques",
  "Service cash",
  "Change devise",
  "Matériel médical",
  "Verrerie",
  "Emballage",
  "Fabrication De Boite Métallique",
  "Lavage de voiture et vidange",
  "Service d'hygiène",
  "Pressing",
  "Entreprise de désinfection",
  "Vente tenues de travail",
  "Vente équipement de pêche",
  "Vente équipement de chasse",
  "Déménagement",
  "Société de recherche de pétrole",
  "Photovoltaïques",
  "Médecine généraliste",
  "Pédiatrie",
  "Psychiatre",
  "Gynécologue",
  "Allergologue",
  "Neurologue",
  "Dentiste",
  "Ophtalmologiste",
  "Diabétologue",
  "Dermatologue",
  "Médecine cardiovasculaire",
  "Anatomo-cytopathologiste",
  "Anesthésiste-réanimateur",
  "Médecine du travail",
  "Médecine du sport",
  "Hépato-gastro-entérologue",
  "Biologiste médicale",
  "Médecine intensive-réanimation",
  "Médecine nucléaire",
  "Médecine physique réadaptateur",
  "Oncologue",
  "Pneumologue",
  "Radiologue et imagerie médicale",
  "Chirurgien pédiatrique",
  "Chirurgien maxillo facial stomatologue",
  "Chirurgien orthopédiste traumatologue",
  "Chirurgien thoracique et cardiovasculaire",
  "Chirurgien vasculaire",
  "Chirurgien viscérale et digestive",
  "Gynécologue obstétricien",
  "Neurochirurgien",
  "Oto-Rhino-Laryngologiste",
  "Urologue",
  "Biologie de la reproduction",
  "Hématologue et immunologiste",
  "Médecine moléculaire, génétique et pharmacologie",
  "Avocat à la cour d'appel",
  "Avocat à la cour de cassation",
  "Avocat",
  "Prêt à porter",
  "Chaussures",
  "Cuisine",
  "Tapis et rideaux",
  "Moquette",
  "Garderie scolaire",
  "Crèche",
  "Jardin d'enfants",
  "Centre de soutien scolaire",
  "Ecole",
  "Lycée",
  "Faculté",
  "Trottinette",
  "Calèche",
  "Train",
  "Quad",
  "Ooredo",
  "Orange",
  "Topnet",
  "Hexabyte",
  "Lyca",
  "Tunisie télécom",
  "Global net",
  "Mécanique avion",
  "Vendeur(showroom)",
  "Pneumatique",
  "Vente piéce de rechange",
  "Ferrailleurs",
  "Diagnostique",
  "Remorquage",
  "Mécanique navale",
  "Carrossier",
  "Mécanique Véhicule",
  "Mécanicien",
  "Cycliste",
  "Moutons",
  "Volailles et oiseaux",
  "Lapins",
  "Chevaux",
  "Escargot",
  "Abeilles",
  "Poisson",
  "Fourage",
  "Embalage thon et sardine",
  "Carton",
  "Fer"
  ];

  const gouvernorats = [
    {
      "Ariana": {
        "image_url": "/gouvernorats/Ariena.jpg",
        "delegations": [
          "Ariana Ville", "La Soukra", "Ettadhamen", "Raoued", "Mnihla", 
          "Kalâat el-Andalous", "Sidi Thabet"
        ]
      }
    },
    {
      "Béja": {
        "image_url": "/gouvernorats/Béja.jpg",
        "delegations": [
          "Béja Nord", "Nefza", "Medjez el-Bab", "Béja Sud", "Testour", 
          "Téboursouk", "Amdoun", "Goubellat", "Thibar"
        ]
      }
    },
    {
      "Ben Arous": {
        "image_url": "/gouvernorats/Ben Arous.jpg",
        "delegations": [
          "El Mourouj", "Fouchana", "Mornag", "Mohamedia", "Radès", 
          "Medina Jedida", "Hammam Lif", "Ben Arous", "Ezzahra", 
          "Bou Mhel el-Bassatine", "Hammam Chott", "Mégrine"
        ]
      }
    },
    {
      "Bizerte": {
        "image_url": "/gouvernorats/bizerte.jpg",
        "delegations": [
          "Bizerte Nord", "Menzel Bourguiba", "Ras Jebel", "Mateur", 
          "Bizerte Sud", "Sejnane", "Menzel Jemil", "Joumine", 
          "Ghezala", "El Alia", "Zarzouna", "Tinja", "Ghar El Melh", "Utique"
        ]
      }
    },
    {
      "Gabès": {
        "image_url": "/gouvernorats/gabes.jpg",
        "delegations": [
          "El Hamma", "Gabès Sud", "Mareth", "Gabès Médina", "Gabès Ouest", 
          "Métouia", "Ghannouch", "Nouvelle Matmata", "Menzel El Habib", "Matmata"
        ]
      }
    },
    {
      "Gafsa": {
        "image_url": "/gouvernorats/gafsa.jpg",
        "delegations": [
          "Gafsa Sud", "Métlaoui", "Sened", "El Ksar", "Moularès", "Redeyef", 
          "El Guettar", "Belkhir", "Mdhilla", "Gafsa Nord", "Sidi Aïch"
        ]
      }
    },
    {
      "Jendouba": {
        "image_url": "/gouvernorats/jendouba.jpg",
        "delegations": [
          "Jendouba Sud", "Ghardimaou", "Fernana", "Tabarka", "Jendouba Nord", 
          "Balta-Bou Aouane", "Aïn Draham", "Bou Salem", "Oued Meliz"
        ]
      }
    },
    {
      "Kairouan": {
        "image_url": "/gouvernorats/Kairouan.jpg",
        "delegations": [
          "Kairouan Nord", "Kairouan Sud", "Bou Hajla", "Sbikha", "Haffouz", 
          "Nasrallah", "Oueslatia", "Hajeb El Ayoun", "Chebika", "El Alâa", 
          "Echrarda"
        ]
      }
    },
    {
      "Kasserine": {
        "image_url": "/gouvernorats/kasserine.jpg",
        "delegations": [
          "Sbeïtla", "Kasserine Nord", "Fériana", "Sbiba", "Foussana", "Thala", 
          "Majel Bel Abbès", "Kasserine Sud", "Ezzouhour", "El Ayoun", 
          "Hassi El Ferid", "Jedelienne", "Haïdra"
        ]
      }
    },
    {
      "Kébili": {
        "image_url": "/gouvernorats/kebili.jpg",
        "delegations": [
          "Kébili Sud", "Kébili Nord", "Souk Lahad", "Douz Nord", "Douz Sud", 
          "Faouar"
        ]
      }
    },
    {
      "La Manouba": {
        "image_url": "/gouvernorats/Mannouba.jpg",
        "delegations": [
          "Douar Hicher", "Oued Ellil", "La Manouba", "Tebourba", "Djedeida", 
          "Mornaguia", "El Batan", "Borj El Amri"
        ]
      }
    },
    {
      "Mahdia": {
        "image_url": "/gouvernorats/mahdia.jpg",
        "delegations": [
          "Mahdia", "Ksour Essef", "Essouassi", "El Jem", "Sidi Alouane", 
          "Bou Merdes", "Chorbane", "Chebba", "Ouled Chamekh", "Melloulèche", 
          "Hebira"
        ]
      }
    },
    {
      "Médenine": {
        "image_url": "/gouvernorats/medenine.jpg",
        "delegations": [
          "Zarzis", "Ben Gardane", "Djerba - Houmt Souk", "Djerba - Midoun", 
          "Médenine Nord", "Médenine Sud", "Beni Khedache", "Djerba - Ajim", 
          "Sidi Makhlouf"
        ]
      }
    },
    {
      "Monastir": {
        "image_url": "/gouvernorats/monastir.jpg",
        "delegations": [
          "Monastir", "Moknine", "Jemmal", "Ksar Hellal", "Téboulba", 
          "Ksibet el-Médiouni", "Bembla", "Zéramdine", 
          "Sayada-Lamta-Bou Hajar", "Sahline", "Ouerdanine", "Bekalta", "Beni Hassen"
        ]
      }
    },
    {
      "Nabeul": {
        "image_url": "/gouvernorats/nabeul.jpg",
        "delegations": [
          "Hammamet", "Korba", "Nabeul", "Menzel Temime", "Grombalia", "Kélibia", 
          "Soliman", "Dar Chaâbane El Fehri", "El Haouaria", "Béni Khiar", 
          "Béni Khalled", "Menzel Bouzelfa", "Bou Argoub", "El Mida", "Takelsa", 
          "Hammam Ghezèze"
        ]
      }
    },
    {
      "Sfax": {
        "image_url": "/gouvernorats/sfax.jpg",
        "delegations": [
          "Sfax Ville", "Sfax Ouest", "Sfax Sud", "Sakiet Eddaïer", "Sakiet Ezzit", 
          "Bir Ali Ben Khalifa", "Thyna", "Jebiniana", "El Hencha", "Agareb", 
          "Menzel Chaker", "Mahrès", "Skhira", "El Amra", "Graïba", "Kerkennah"
        ]
      }
    },
    {
      "Sidi Bouzid": {
        "image_url": "/gouvernorats/Sidi Bouzid.jpg",
        "delegations": [
          "Sidi Bouzid Ouest", "Regueb", "Sidi Bouzid Est", "Jilma", "Bir El Hafey", 
          "Sidi Ali Ben Aoun", "Menzel Bouzaiane", "Mezzouna", "Meknassy", 
          "Ouled Haffouz", "Souk Jedid", "Cebbala Ouled Asker"
        ]
      }
    },
    {
      "Siliana": {
        "image_url": "/gouvernorats/siliana.jpg",
        "delegations": [
          "Makthar", "Rouhia", "Siliana Sud", "Siliana Nord", "El Krib", 
          "Bou Arada", "Gaâfour", "Kesra", "Sidi Bou Rouis", "Bargou", "El Aroussa"
        ]
      }
    },
    {
      "Sousse": {
        "image_url": "/gouvernorats/sousse.jpg",
        "delegations": [
          "M'saken", "Sousse Riadh", "Sousse Jawhara", "Kalâa Kebira", 
          "Sousse Sidi Abdelhamid", "Enfida", "Hammam Sousse", "Sousse Médina", 
          "Kalâa Seghira", "Akouda", "Bouficha", "Sidi Bou Ali", "Kondar", 
          "Sidi El Hani", "Hergla"
        ]
      }
    },
    {
      "Tataouine": {
        "image_url": "/gouvernorats/tataouine.jpg",
        "delegations": [
          "Tataouine Nord", "Tataouine Sud", "Ghomrassen", "Smâr", "Remada", 
          "Bir Lahmar", "Dehiba"
        ]
      }
    },
    {
      "Tozeur": {
        "image_url": "/gouvernorats/Touzeur.png",
        "delegations": [
          "Tozeur", "Degache", "Nefta", "Tameghza", "Hazoua"
        ]
      }
    },
    {
      "Tunis": {
        "image_url": "/gouvernorats/tunis.jpg",
        "delegations": [
          "Hraïria", "El Kabaria", "Sidi Hassine", "La Marsa", "Le Bardo", 
          "El Omrane supérieur", "Le Kram", "El Menzah", "El Omrane", "Ezzouhour", 
          "Bab El Bhar", "Cité El Khadra", "Séjoumi", "El Ouardia", "Bab Souika", 
          "Sidi El Béchir", "La Goulette", "Médina", "Djebel Jelloud", "Ettahrir", 
          "Carthage"
        ]
      }
    },
    {
      "Zaghouan": {
        "image_url": "/gouvernorats/Zaghouane.jpg",
        "delegations": [
          "El Fahs", "Zaghouan", "Nadhour", "Bir Mcherga", "Zriba", 
          "Saouaf"
        ]
      }
    },
    {
      "Kef": {
        "image_url": "/gouvernorats/kef.jpg",
        "delegations": [
          "Kef Est", "Dahmani", "Tajerouine", "Kef Ouest", "Nebeur", "Sers", 
          "Sakiet Sidi Youssef", "El Ksour", "Kalaat Senan", "Jérissa", 
          "Kalâat Khasba"
        ]
      }
    }
  ]
  
  
    // State variables to control popups
    const [showCountryPopup, setShowCountryPopup] = useState(false);
    const [showRegionPopup, setShowRegionPopup] = useState(false);
    const [showCategoryPopup, setShowCategoryPopup] = useState(false);
    const [showActivityPopup, setShowActivityPopup] = useState(false);
    const [showAdvancedSearchPopup, setShowAdvancedSearchPopup] = useState(false);
  const sortedcategories = useMemo(() => {
        return [...categories].sort((a, b) =>
          a.localeCompare(b, 'fr', { sensitivity: 'base' })
        );
      }, [categories]);
    // Function to handle the search button click
    const handleSearch = () => {
      // Navigate to the Users component with search parameters
      navigate("/searchresult", {
        state: {
          searchParams: {
            country,
            region,
            category,
            activity,
          },
          gouvernoratData: gouvernorats.find((g) => g[region])?.[region],
        },
      });
    };
  
    // Handle Popup toggle
    const togglePopup = (type) => {
      switch (type) {
        case "country":
          setShowCountryPopup(!showCountryPopup);
          break;
        case "region":
          setShowRegionPopup(!showRegionPopup);
          break;
        case "category":
          setShowCategoryPopup(!showCategoryPopup);
          break;
        case "activity":
          setShowActivityPopup(!showActivityPopup);
          break;
        case "advanced":
          setShowAdvancedSearchPopup(!showAdvancedSearchPopup);
          break;
        default:
          setShowCountryPopup(false);
          setShowRegionPopup(false);
          setShowCategoryPopup(false);
          setShowActivityPopup(false);
          setShowAdvancedSearchPopup(false);
      }
    };
  
    // Close all popups when clicking outside
    useEffect(() => {
      const closePopupsOnOutsideClick = (e) => {
        if (!e.target.closest('.popup') && !e.target.closest('.search-section-saerch')) {
          setShowCountryPopup(false);
          setShowRegionPopup(false);
          setShowCategoryPopup(false);
          setShowActivityPopup(false);
          setShowAdvancedSearchPopup(false);
        }
      };
  
      document.addEventListener('click', closePopupsOnOutsideClick);
      return () => document.removeEventListener('click', closePopupsOnOutsideClick);
    }, []);
  
    return (
      <div className="header-container">
        <div className="search-container-saerch">
          <div className="search-section-saerch">
            <label htmlFor="country">{t("Pays")}</label>
            <input
              type="text"
              id="country"
              value={country}
              onClick={() => togglePopup("country")}
              onChange={(e) => setCountry(e.target.value)}
              placeholder={t("Enter Un Pays")}
            />
            {showCountryPopup && (
              <div className="popup">
                <div className="popup-content">
                  <input 
                    type="text" 
                    placeholder="Filter Pays"
                    onChange={(e) => setCountry(e.target.value)}
                  />
                  <ul>
                    {countries.filter(c => c.toLowerCase().includes(country.toLowerCase())).map((country, index) => (
                      <li key={index} onClick={() => { setCountry(country); togglePopup("country"); }}>
                        {country}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
  
          <div className="search-section-saerch">
            <label htmlFor="region">{t("Ville")}</label>
            <input
              type="text"
              id="region"
              value={region}
              onClick={() => togglePopup("region")}
              onChange={(e) => setRegion(e.target.value)}
              placeholder={t("Entrer Une Ville")}
            />
            {showRegionPopup && (
              <div className="popup">
                <div className="popup-content">
                  <input 
                    type="text" 
                    placeholder="Filter Ville"
                    onChange={(e) => setRegion(e.target.value)}
                  />
                  <ul>
                    {regions_tunisie.filter(r => r.toLowerCase().includes(region.toLowerCase())).map((region, index) => (
                      <li key={index} onClick={() => { setRegion(region); togglePopup("region"); }}>
                        {region}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
  
          <div className="search-section-saerch">
            <label htmlFor="category">{t("Services")}</label>
            <input
              type="text"
              id="category"
              value={category}
              onClick={() => togglePopup("category")}
              onChange={(e) => setCategory(e.target.value)}
              placeholder={t("Entrer Un Service")}
            />
            {showCategoryPopup && (
              <div className="popup">
                <div className="popup-content">
                  <input 
                    type="text" 
                    placeholder="Filter Services"
                    onChange={(e) => setCategory(e.target.value)}
                  />
                  <ul>
                    {sortedcategories.filter(c => c.toLowerCase().includes(category.toLowerCase())).map((category, index) => (
                      <li key={index} onClick={() => { setCategory(category); togglePopup("category"); }}>
                        {category}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
  
          <div className="search-section-saerch">
            <label htmlFor="activity">{t("Mot Clé")}</label>
            <input
              type="text"
              id="activity"
              value={activity}
              onClick={() => togglePopup("activity")}
              onChange={(e) => setActivity(e.target.value)}
              placeholder={t("Enter activités")}
            />
            {showActivityPopup && (
              <div className="popup">
                <div className="popup-content">
                  <input 
                    type="text" 
                    placeholder="Filter Service"
                    onChange={(e) => setActivity(e.target.value)}
                  />
                  <ul>
                    {services.filter(s => s.toLowerCase().includes(activity.toLowerCase())).map((service, index) => (
                      <li key={index} onClick={() => { setActivity(service); togglePopup("activity"); }}>
                        {service}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
  
          <button className="search-btn-saerch" onClick={handleSearch}>
            <i className="fas fa-search"><IoSearch /></i>
          </button>
        </div>
  
        {showAdvancedSearchPopup && (
          <div className="popup">
            <div className="popup-content">
              <input 
                type="text" 
                placeholder="Advanced Search"
              />
              <ul>{services}
              </ul>
            </div>
          </div>
        )}
           
      </div>
      
    );
    
  }
  
  export default Header;